WITH "missing_participant_codes" AS (
	SELECT
		"id",
		(
			COALESCE((SELECT MAX("source_record_id") FROM "participants"), 0)
			+ ROW_NUMBER() OVER (ORDER BY "created_at", "id")
		)::integer AS "source_record_id"
	FROM "participants"
	WHERE "source_record_id" IS NULL
)
UPDATE "participants"
SET "source_record_id" = "missing_participant_codes"."source_record_id"
FROM "missing_participant_codes"
WHERE "participants"."id" = "missing_participant_codes"."id";
--> statement-breakpoint
ALTER TABLE "participants" ALTER COLUMN "source_record_id" SET NOT NULL;
--> statement-breakpoint
ALTER TABLE "participants" ALTER COLUMN "source_record_id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "participants_source_record_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);
--> statement-breakpoint
SELECT setval(
	'participants_source_record_id_seq',
	COALESCE((SELECT MAX("source_record_id") FROM "participants"), 0) + 1,
	false
);
